### ISSUE TITLE
При запуске парсера выдает ошибку

### ISSUE THREAD

**Issue by VegasChickiChicki** [iren-coder/Yandex_and_Ozon_news_parsing_Test_case#1]
Traceback (most recent call last):
  File "C:\work-projects\popso-backend-tests\Yandex_and_Ozon_news_parsing_Test_case-main\parser.py", line 170, in <module>
    main()
  File "C:\work-projects\popso-backend-tests\Yandex_and_Ozon_news_parsing_Test_case-main\parser.py", line 166, in main
    save_data_to_csv(ozon_data, filename="ozon_data.csv")
  File "C:\work-projects\popso-backend-tests\Yandex_and_Ozon_news_parsing_Test_case-main\parser.py", line 147, in save_data_to_csv
    for row in range(0, len(data["titles"])):
TypeError: 'NoneType' object is not subscriptable

**Comment by VegasChickiChicki** [comment]
Полный текст ошибки:

[INFO][12:48:19] Parser started!

DevTools listening on ws://127.0.0.1:61479/devtools/browser/dd73a857-41a7-4134-b9af-37cb934aadfa
[INFO][12:48:22] Failed connection to "ozon.ru"!
[INFO][12:48:22] Successful connection to "yandex.ru"!
[INFO][12:48:23] Parser "yandex.ru" was finished!
[INFO][12:48:24] Data is saved in "yandex_data.csv"
Traceback (most recent call last):
  File "C:\work-projects\popso-backend-tests\Yandex_and_Ozon_news_parsing_Test_case-main\parser.py", line 170, in <module>
    main()
  File "C:\work-projects\popso-backend-tests\Yandex_and_Ozon_news_parsing_Test_case-main\parser.py", line 166, in main
    save_data_to_csv(ozon_data, filename="ozon_data.csv")
  File "C:\work-projects\popso-backend-tests\Yandex_and_Ozon_news_parsing_Test_case-main\parser.py", line 147, in save_data_to_csv
    for row in range(0, len(data["titles"])):
TypeError: 'NoneType' object is not subscriptable

**Comment by VegasChickiChicki** [comment]
Проблема была в версии вебдрейвера для хрома, необходимо это указать в документации к проекту.
